import { defineObject, FieldType } from 'twenty-sdk/define';

import {
  ORDER_DISCOUNT_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  ORDER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  ORDER_NOTES_FIELD_UNIVERSAL_IDENTIFIER,
  ORDER_OBJECT_UNIVERSAL_IDENTIFIER,
  ORDER_REMAINING_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
  ORDER_SOURCE_FIELD_UNIVERSAL_IDENTIFIER,
  ORDER_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
  ORDER_TOTAL_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
} from 'src/constants/universal-identifiers';

export enum OrderStatus {
  NEW = 'NEW',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum OrderSource {
  WEBSITE = 'WEBSITE',
  EVENT = 'EVENT',
  FAIR = 'FAIR',
  REFERRAL = 'REFERRAL',
  SOCIAL_ADS = 'SOCIAL_ADS',
  FANPAGE = 'FANPAGE',
  ZALO = 'ZALO',
  OTHER = 'OTHER',
}

export default defineObject({
  universalIdentifier: ORDER_OBJECT_UNIVERSAL_IDENTIFIER,
  nameSingular: 'order',
  namePlural: 'orders',
  labelSingular: 'Order',
  labelPlural: 'Orders',
  description: 'Customer sales orders and payment tracking',
  icon: 'IconShoppingCart',
  labelIdentifierFieldMetadataUniversalIdentifier:
    ORDER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
  fields: [
    {
      universalIdentifier: ORDER_NAME_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'name',
      label: 'Order Code',
      description: 'Order code (e.g. OD00031)',
      icon: 'IconReceipt',
    },
    {
      universalIdentifier: ORDER_TOTAL_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'totalAmount',
      label: 'Total Amount',
      icon: 'IconCoin',
      isNullable: true,
    },
    {
      universalIdentifier: ORDER_DISCOUNT_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'discountAmount',
      label: 'Discount',
      icon: 'IconDiscount2',
      isNullable: true,
    },
    {
      universalIdentifier: ORDER_REMAINING_AMOUNT_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.CURRENCY,
      name: 'remainingAmount',
      label: 'Remaining Balance',
      icon: 'IconCreditCard',
      isNullable: true,
    },
    {
      universalIdentifier: ORDER_SOURCE_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'orderSource',
      label: 'Source',
      icon: 'IconWorld',
      defaultValue: `'${OrderSource.WEBSITE}'`,
      options: [
        {
          id: '1a1a1a1a-1a1a-4a1a-8a1a-1a1a1a1a1a1a',
          value: OrderSource.WEBSITE,
          label: 'Website',
          position: 0,
          color: 'blue',
        },
        {
          id: '2b2b2b2b-2b2b-4b2b-8b2b-2b2b2b2b2b2b',
          value: OrderSource.EVENT,
          label: 'Event',
          position: 1,
          color: 'green',
        },
        {
          id: '3c3c3c3c-3c3c-4c3c-8c3c-3c3c3c3c3c3c',
          value: OrderSource.FAIR,
          label: 'Fair / Expo',
          position: 2,
          color: 'yellow',
        },
        {
          id: '4d4d4d4d-4d4d-4d4d-8d4d-4d4d4d4d4d4d',
          value: OrderSource.REFERRAL,
          label: 'Referral',
          position: 3,
          color: 'purple',
        },
        {
          id: '5e5e5e5e-5e5e-4e5e-8e5e-5e5e5e5e5e5e',
          value: OrderSource.SOCIAL_ADS,
          label: 'Social Ads',
          position: 4,
          color: 'red',
        },
        {
          id: '6f6f6f6f-6f6f-4f6f-8f6f-6f6f6f6f6f6f',
          value: OrderSource.FANPAGE,
          label: 'Facebook Fanpage',
          position: 5,
          color: 'blue',
        },
        {
          id: '7a7a7a7a-7a7a-4a7a-8a7a-7a7a7a7a7a7a',
          value: OrderSource.ZALO,
          label: 'Zalo OA',
          position: 6,
          color: 'sky',
        },
        {
          id: '8b8b8b8b-8b8b-4b8b-8b8b-8b8b8b8b8b8b',
          value: OrderSource.OTHER,
          label: 'Other',
          position: 7,
          color: 'gray',
        },
      ],
    },
    {
      universalIdentifier: ORDER_STATUS_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.SELECT,
      name: 'status',
      label: 'Status',
      icon: 'IconProgress',
      defaultValue: `'${OrderStatus.NEW}'`,
      options: [
        {
          id: '9c9c9c9c-9c9c-4c9c-8c9c-9c9c9c9c9c9c',
          value: OrderStatus.NEW,
          label: 'New',
          position: 0,
          color: 'blue',
        },
        {
          id: '0d0d0d0d-0d0d-4d0d-8d0d-0d0d0d0d0d0d',
          value: OrderStatus.PROCESSING,
          label: 'Processing',
          position: 1,
          color: 'orange',
        },
        {
          id: '1e1e1e1e-1e1e-4e1e-8e1e-1e1e1e1e1e1e',
          value: OrderStatus.COMPLETED,
          label: 'Completed',
          position: 2,
          color: 'green',
        },
        {
          id: '2f2f2f2f-2f2f-4f2f-8f2f-2f2f2f2f2f2f',
          value: OrderStatus.CANCELLED,
          label: 'Cancelled',
          position: 3,
          color: 'red',
        },
      ],
    },
    {
      universalIdentifier: ORDER_NOTES_FIELD_UNIVERSAL_IDENTIFIER,
      type: FieldType.TEXT,
      name: 'notes',
      label: 'Notes',
      description: 'Order instructions, delivery or customer notes',
      icon: 'IconNotes',
      isNullable: true,
    },
  ],
});
