/*
 * _____                    _
 *|_   _|_      _____ _ __ | |_ _   _
 *  | | \ \ /\ / / _ \ '_ \| __| | | | Auto-generated file
 *  | |  \ V  V /  __/ | | | |_| |_| | Any edits to this will be overridden
 *  |_|   \_/\_/ \___|_| |_|\__|\__, | Generated by: npx nx version:bump twenty-server
 *                              |___/
 */

<<<<<<< HEAD
export const TWENTY_NEXT_VERSIONS = ['2.40.0'] as const;
=======
export const TWENTY_NEXT_VERSIONS = [
  '2.41.0',
] as const;
>>>>>>> twenty/v2.40.0
